compat: flower: fix incorrect function return type
Seems like somewhere during the compatibility updates the return type
of 'nfp_flower_tun_is_gre()' got incorrectly updated. This leads to the
following error on newer gcc versions:
    error: implicit conversion from ‘enum <anonymous>’
    to ‘enum nfp_flower_tun_type’

Checking the function use this should very clearly return 'bool', and
this is also what the upstream version is doing. This patch updates the
return type to 'bool', instead of 'enum nfp_flower_tun_type'.

Signed-off-by: Louis Peens <louis.peens@corigine.com>
Reviewed-by: Ryno Swart <ryno.swart@corigine.com>