nfp: crdma: fix wrong dependence on intel_auxiliary
We use auxiliary to decouple rdma and nfp driver in higher kernel
version. In some linux distributions will be integrated with
intel_auxiliary, just like 5.10.0-200.0.0.113.25.oe2203sp3.bclinux,
intel_auxiliary is conflicted with auxiliary:

modprobe intel_auxiliary
modprobe: ERROR: could not insert 'intel_auxiliary': Exec format error
dmesg | tail -n 1
intel_auxiliary: exports duplicate symbol
__auxiliary_device_add (owned by kernel)

It is a issue raised by linux distribution, but we need to adapt it.
If intel_auxiliary is integrated, we will use function callback
instead of auxiliary.

Signed-off-by: Guibin Xia <guibin.xia@corigine.com>
Signed-off-by: Xiaofeng Tang <xiaofeng.tang@corigine.com>
Signed-off-by: Louis Peens <louis.peens@corigine.com>